/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/house.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['BuildingMesh-00000'].geometry}
        material={materials['BuildingMat-00000']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00006'].geometry}
        material={materials['BuildingMat-00006']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00008'].geometry}
        material={materials['BuildingMat-00008']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00011'].geometry}
        material={materials['BuildingMat-00011']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00022'].geometry}
        material={materials['BuildingMat-00022']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00023'].geometry}
        material={materials['BuildingMat-00023']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00026'].geometry}
        material={materials['BuildingMat-00026']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00031'].geometry}
        material={materials['BuildingMat-00031']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00037'].geometry}
        material={materials['BuildingMat-00037']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00215'].geometry}
        material={materials['BuildingMat-00215']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00220'].geometry}
        material={materials['BuildingMat-00220']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes['BuildingMesh-00223'].geometry}
        material={materials['BuildingMat-00223']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/house.gltf')
